source/conf.py, source/installation.rst
It was difficult to scan for macOS instructions in the docs, so I moved the Homebrew instructions into a tab under a new macOS section. I think it looks fine with a single tab. A target element was added so that old hyperlinks to `#homebrew` will still work.
I also bumped the copyright year.
=>  Replace Homebrew section with macOS section

source/scripting.rst
=> Fix njs syntax in example

source/community.rst, source/installation.rst
Now that we have switched to Git & GitHub as our primary VCS and repository hosting environment. This updates the community and installation pages to make GitHub the primary location for our repositories and our internally hosted Mercurial repositories to be the mirrors.
A second patch removes all mentions Mercurial.
=> GitHub is now our primary repository hosting environment

source/howto/samples.rst
These semicolons in the Go example are ineffectual and should be removed.
=> Remove unnecessary semicolons from Go example

netlify.toml
This draft PR adds a [netlify.toml](https://docs.netlify.com/routing/redirects/redirect-options/) file for redirects. In its current state, it redirects downloads from https://unit.nginx.org/download/ to https://sources.nginx.org/unit/ which does not yet exist. 
~~Blocked by: #75~~ https://sources.nginx.org/unit/ is now live.
=> Add netlify.toml file for redirects

netlify.toml, source/howto/modules.rst, source/installation.rst
The links on https://nginx-unit.netlify.app/download are relative and do not correctly correspond to the correct path. Instead of mangling the index to update the links to keep it on unit.nginx.org, we can just redirect the index separately from direct requests for the tarballs. The glob redirect still works for those links.
These relative links are missing /download in the path, because of the move to sources.nginx.org.
=> Update netlify.toml redirects

Makefile
These files are guaranteed to have unique filenames because they originate from source/downloads together.
The end result:
```
tree -lh deploy/_downloads
[ 640]  deploy/_downloads
├── [  96]  077feed4aa66df9c8eba6520fdfcae65
│   └── [1.3K]  Dockerfile.php.txt
├── [  96]  55f3fadb10a1bec1c359757ae72cb998
│   └── [2.5K]  Dockerfile.go.txt
├── [  96]  57c3dbaa35e8622ad7cfc7dd1b281c01
│   └── [1.9K]  Dockerfile.ruby.txt
├── [  96]  626b50fd97c76a7215539b7bd884cf2c
│   └── [1.8K]  grafana.patch
├── [  96]  8b892abde1148c9ef4f41e16953cd590
│   └── [1.6K]  Dockerfile.python.txt
├── [2.5K]  Dockerfile.go.txt
├── [1.5K]  Dockerfile.java.txt
├── [1.9K]  Dockerfile.nodejs.txt
├── [1.9K]  Dockerfile.perl.txt
├── [1.3K]  Dockerfile.php.txt
├── [1.6K]  Dockerfile.python.txt
├── [1.9K] …
```
=> Copy files from deploy/_downloads subdirectories into _downloads

source/configuration.rst, source/howto/laravel.rst, source/howto/responder.rst, source/installation.rst
Addresses many of the broken links in #80.
Notable changes include openports.se -> pkgsrc.se and an IETF link. The rest are just page anchors.
=> Link fixes

source/404.html, source/conf.py
Netlify's default 404 page displays links to Netlify's support forums and pages. For now, we're defaulting to a plain NGINX-style 404.html.
=> Add 404.html to replace default Netlify error page

source/howto/modules.rst
Both the WebAssembly modules, wasm & wasm-wasi-component are internal modules. I.e they are both loaded by Unit as DSO's and run under the direct control of Unit in prototype/application processes.
=> WebAssembly is an 'internal' language module

source/news/2024/unit-1.32.0-released.rst
Timo
PR to address this feedback from @callahad :
At a very high level:
=> Release 1.32 rewrite news doc

source/news/2024/unit-1.32.0-released.rst
Corrects two items in the release notes.
=> release news corrections

source/howto/source.rst
=> Add missing backticks around command line instruction

source/howto/docker.rst
[nginx/unit](https://hub.docker.com/r/nginx/unit) is deprecated. [unit](https://hub.docker.com/_/unit) is the official name now.
=> Fix outdated Docker image name

source/configuration.rst, source/news/2023/index.rst, source/news/2024/index.rst, source/news/2024/unit-1.32.0-released.rst, source/news/2024/unit-1.32.1-released.rst
Changes some instances of NJS to njs (which is the preferred way to write it)
Does not change:
- References to njs in code blocks
- Rererences to njs in changelog (as these are a copy paste of the releases changelog)
Fixes issue:  https://github.com/nginx/unit-docs/issues/132
=> fix: njs should be lowercase

source/community.rst, source/go, source/howto/modules.rst, source/installation.rst, source/news/2018/unit-1.4-released.rst, source/theme/layout.html
We have switched from internally hosted mercurial repositories to GitHub hosted git repositories as our source of truth.
=> Switch hg to git in various places

source/community.rst
Updates the community page to split the content into sections.
Removes the link to slack and prioritizes GitHub issues as means of communication.
=> docs: overhaul community page

source/community.rst
fix a link in the community page.
after:
=> fix: Malformed link on the community page

source/howto/source.rst
Update the `Enabling njs` steps to include changing branches to the latest supported version
=> docs: update njs build instructions

source/conf.py, source/exts/github.py, source/theme/layout.html, source/theme/static/style.css
I've done some hard coding. (I couldn't figure out how to set this up "properly." But since this applies to all pages, I'm not sure if that matters.)
I don't claim to know any/all PR requirements -- I'm using this as a learning experience.
Ref #150 and https://github.com/nginx/unit/pull/1299
Here's how it looks in the local build.
=> Include a "standard" link to the list of discussions

source/contents.rst, source/controlapi.rst, source/statusapi.rst, source/usagestats.rst
Adds the `modules` object documentation to the Usage Statistics document
=> docs: add modules to usagestats

source/contents.rst, source/unitctl.rst
Adds the doc for the unitctl cli
To do:
- Add the links to the binaries or remove the section
- Decide whether to add the compiling instructions here or keep them as a link to the repo
=> docs: add CLI doc

source/news/2024/unit-1.33.0-released.rst, source/unitctl.rst
Adds a "early access" note to unitctl in the release notes and the unitctl doc.
=> docs: add unitctl note

source/configuration/index.rst
Update the configuration doc as per #178
=> docs: update configuration:applications

source/certificates.rst, source/configuration/index.rst, source/controlapi.rst, source/howto/apollo.rst, source/howto/certbot.rst, source/howto/express.rst, source/howto/grafana.rst, source/howto/koa.rst, source/howto/mailman.rst, source/howto/mediawiki.rst, source/howto/modules.rst, source/howto/nextcloud.rst, source/howto/roundcube.rst, source/howto/samples.rst, source/howto/security.rst, source/howto/source.rst, source/include/howto_change_ownership.rst, source/include/howto_upload_config.rst, source/installation.rst, source/scripting.rst, source/troubleshooting.rst
Adds notes to make readers aware of which commands need to be run as root, in two ways:
- In docs where there are 1 or 2 root commands, it adds a note in the step before the command
- In docs with many root commands, it adds a note callout in the introductory section of the page
Closes #171
=> docs: add notes about root requirements for commands

source/news/2025/unit-1.34.2-released.rst
The changelog didn't appear in the code block due to insufficient indentation.
=> Fix 1.34.2 release notes changelog
